name 'danielkza-redelinux'
version '0.1'
author 'Daniel Miranda (danielkza)'
license 'Apache 2'

dependency 'puppetlabs-apt'
dependency 'puppetlabs-stdlib'
dependency 'danielkza-video_device'
dependency 'ploperations-interval'
dependency 'ripienaar-concat'

source 'https://github.com/danielkza/puppet-redelinux'
project_page 'https://github.com/danielkza/puppet-redelinux'
